### ISSUE TITLE
Flightpaths missing from world map among other things...

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite#53]
First thing:
3-4 days ago, the flight paths on my Carbonite Map disappeared entirely. I have none, not just in Legion but even in Orgrimmar, my Garrison, Dalaran (Legion and LK) - everywhere, they're not there. It's not that I need them desperately, but sometimes I want to get from X to Y while not being in front of the PC and the fastest and easiest way to do that is through a flight path - they're hard to track on a Map they're not visually on.
However, when I mouse over a place where I know for a fact that there is a Flightmaster, the name pops up in a text box on the Map eg. Sylvan Falls, Highmountain 
![image](https://user-images.githubusercontent.com/31900265/30342806-67074480-97fb-11e7-9d8f-ef6d3c57dd51.png) https://imgur.com/xJbkIt5 (in case the img fails.

I haven't gotten any errors that I've noticed related to this particular issue. They were just there one minute and gone the next. This goes for ALL my toons, those at lvl 1 and up to 110.

I consider my self an avid carbonite user as I've used it since a week in to TBC expansion and ever since then... I have not been able to find anywhere if I've by mistake turned it off. I prefer as little crap on my map as possible, which is also why herbs, mines, timber, POI's is turned off.

Second thing:
Which reminds me... I have Archaeology Blops turned off (when I right click the Map and click on Show, it's turned off) but the Archaeology Blops are still on my Map (for this week it's Stormheim due to the Quest from an NPC in Dalaran (those two are related, so it probably changes next week unless it's on it's second week of it's rotation)). shouldn't they be turned off or does that only go for every other Map that isn't a part of Legion? 
![image](https://user-images.githubusercontent.com/31900265/30343376-ab452da4-97fd-11e7-9e70-323d07dd614e.png)

Third thing:
When right clicking the map, we users have option to Show Instance Map which is just above Goto and Clear Goto.. Please, Please, Please move Show Instance Map further down the list like under Monitor Zone when the other check boxes are. 
First of all Show Instance Map is (sorry for the wording) fucking it up for a LONG OLD TIME user like me. It's simply in the way and it's messing with Clear Goto (that I have always used a lot!).. it's just in the way of the mouse position all the time.
Sorry that was personal... but it is in the way of the more useable parts of the right-clicking menu... sadly I have no LUA experience and even looking at some of the LUA for beginners guides it seems daunting, otherwise I would probably sooner rather than later have done it... (maybe, big maybe)
As you can see on the 2 images above... I'm missing flightpath Masters, on the other hand the Map is showing Bonus tasks (that I've completed a long time ago. (I didn't do Loremaster back in LK for nothing, I like to quest))

**Comment by Thrumbar** [comment]
First:  Please check you  Icon Scale  
          Right Click on Carbonite map > select scale and check Icon Scale slider
Second: If the Archaeology Blops is quest related it may show as a quest blob also..  
Third: Pushed a fix as per your request

**Comment by Swirrel** [comment]
My Icon Scale is currently 5.15. I've tried setting it to max - it doesn't change anything.

Digsites are also shown in other parts of WoW.. atm I have 1 digsite in Winterspring, Felwood, Southern Barrens, Feralas, Blasted Lands, Arathi Highlands, Hinterlands, WPL, 2 in Townlong Steppes and Dread Wastes, 3 in Azsuna, 1 in Borean Tundra, Howling Fjord and Icecrown, 1 in Netherstorm, Hellfire Peninsula, 2 in Shadowmoon Valley (TBC), 1 in Spires of Arak, Talador, 2 in Nagrand (Draenor).. 
I have zero (0) archaeology quests in my quest log and that goes for all my other toons on Draenor EU (the server I play on) - I play Horde... dunno if that matters? And the toon in question who I'm experience these strange things on is my Guardian Druid - Tauren Male... Not that I think that should change anything... I also have the issue on my shaman, 2nd druid and the FP issue on my mage.

If you need further info let me know.

**Comment by Swirrel** [comment]
Thank you with regards to the push. I'm assuming that that means that there another smaller update to Carb?

**Comment by mikepauer** [comment]
The show dig site option is concerning the orange circular blobs that show you the boundries of the digsite, not the digging icon.

never really looked into having the option also remove the digging icon aswell, but I will.

The Show instance map, I purposely put it at the top for fast swapping between the two draw modes when you need to map something. I'll consider and weigh how everyone feels about it.

**Comment by Swirrel** [comment]
The Show Instance Map I can understand if it to most would be no big deal and that putting it on top is for easier and faster access to it and if most long time users like my self might not care that much, but I'm fairly positive that should you decide to move it down to the other "check boxes" area, maybe on top of the 3 that are already there, that it too wouldn't be that "big of a deal".. What do I know.. hehe
Moving it from where it is, to another location within the same menu, I have no idea how much of a workload that would be. And it's fine if something else takes priority right now.

**Comment by Swirrel** [comment]
About the digsite icons.. tbh I thought that removing the blobs meant all of it and not just the the red'ish blobs around the actual icon.. again, it's no big, so fix what ever else is much more important. I'll live with the rest...

**Comment by Swirrel** [comment]
Where do I get the "push" that Thrumbar pushed 17 hrs ago?

**Comment by fdellwing** [comment]
Best is to wait for @mikepauer or @IrcDirk to merge #54 and than get newest beta via curse client.

Or look what he changed and change it locally.

**Comment by IrcDirk** [comment]
Pull request merged.

Those archaeology icons arent they from HandyNotes?

**Comment by Palonblade** [comment]
Regarding the FPs not showing, reduce the POI Icons At Scale setting. Not sure why this works but it does

**Comment by Swirrel** [comment]
Palonblade: Reducing or increasing POI icon scale doesn't do anything to my FP's. They're still not there.

IrcDirk: I don't use HandyNotes. I did for a week or two during WoD's early days but HandyNotes didn't function with Carbonite at that time, so I erased the entire thing and never used it since.

fdellwing: Noob inc... I've no idea how to change it. I could probably find it, if I knew where to look and what to look for... sorry...

**Comment by IrcDirk** [comment]
@Swirrel Set map options like this, but at those setting Filght Masters are visible when u zoom in map like that:

![img](https://i.imgur.com/tT20Syc.png)

"Show..." 
![img](https://i.imgur.com/poR59zm.png)

"Scale..." 
![img](https://i.imgur.com/YgydYbJ.png)

If this doesnt help just reset all Carbonite options or delete Carb setting from WTF folder.

**I have fixed those shovel icons, now they disappear when Archaeology Blops is turned off.**

**Comment by Swirrel** [comment]
I don't have the Continent POIs and the FP's are still not there even after following your scale settings. I still have the archy icons. I'll get around to reset Carbonite though I really really dislike doing that. It'll take forever to set it right again due to it being so big and having so many options.

Thank you.

**Comment by IrcDirk** [comment]
U could use Profiles, save old, create new one and reset it.

**Comment by Swirrel** [comment]
I have to figure out how to go about that, seeing as I always forget to make a new one and change that to my liking, instead I just make the changes I like to the default one..
Because I'm lazy in that way, I set it up on 1 toon that I then copy from on all my other toons.  

Am a bit swamped at the moment. I had a board meeting in my apartment complex monday where I was selected head of the board so I'm a little busy/stressed atm.

**Comment by Swirrel** [comment]
So tonight I decided to go farm for Fjarnskaggl in Stormheim and the second I hit Stormheim and turned on Herb Locations and hit the tracking route and asking it to recycle it, carb map spiked from 15mb to 25mb + and carb quest from 10mb and up to the wrong side of 15mb... and had a ton of sluggish lag.
Turning off the tracking, recycling of tracking and herb locations didn't change anything.
I took screenies of all my carbonite settings, shut the game down, removed ALL of carbonite and installed it again through twitch client.
After logging back in, checking that carbonite was turned on, I noticed before anything that I still don't have flight points and archaeology icons are still there. Changing everything to my liking with carbonite haven't changed it. Still no FP's and the archaeology icons are still there... I also noticed when I right clicked on the map and clicked show that I still don't have Show Continent POI's

And stupid here (aka me) yet again didn't make a new profile and left the default alone, but changed it.

You would think that when I remove everything carbonite from my pc (that includes hidden files and folders btw), and get a brand new installation that it would work, right... guess not.

So should I completely remove it again and get it from github, instead of twitch client? and if so, where would I get Carbonite Weekly as github doesn't seem to have that part though twitch does?

The screenies show time stamps, addons running and how much they use each. Also the map can be seen both with and without tracking.

**Comment by Swirrel** [comment]
![wowscrnshot_092217_230357](https://user-images.githubusercontent.com/31900265/30766696-23ebc4b0-9ff7-11e7-9281-cd2f69a2ca00.jpg)
![wowscrnshot_092217_230522](https://user-images.githubusercontent.com/31900265/30766693-23e79b24-9ff7-11e7-84a4-a6be8004a1ea.jpg)
![wowscrnshot_092217_230529](https://user-images.githubusercontent.com/31900265/30766691-23e56dae-9ff7-11e7-8d28-1bf3cb4ed26d.jpg)
![wowscrnshot_092217_230559](https://user-images.githubusercontent.com/31900265/30766692-23e6ea80-9ff7-11e7-8f21-60ca95e24d75.jpg)
![wowscrnshot_092217_230628](https://user-images.githubusercontent.com/31900265/30766694-23e9cdcc-9ff7-11e7-9cc3-03ee3d79d830.jpg)
![wowscrnshot_092217_230744](https://user-images.githubusercontent.com/31900265/30766695-23eb352c-9ff7-11e7-838f-4e44e8cf8b07.jpg)
![wowscrnshot_092217_230824](https://user-images.githubusercontent.com/31900265/30766697-23ff4f3a-9ff7-11e7-99d9-9db609b67064.jpg)

**Comment by mikepauer** [comment]
For the sluggishness, inside your twitch client do you have it set for Alpha releases? there's been work done on that part pushed over the last few days that you would only get using the Alpha version.

Carbonite.weeky is available here on github :) https://github.com/mikepauer?tab=repositories the git overview page only shows the 6 most recent, but everything is here.

**Comment by Swirrel** [comment]
All Carbonite's are now set to Alpha. I've exited the game again and am now updating once again :)

Nice to know that you got weekly too... 

Thank you :D

**Comment by Swirrel** [comment]
I don't know what's wrong. I got the Alpha versions now and still no FP's...

https://imgur.com/a/zzt2Q
It's now public. If you can't find it, my imgur name is GravhundenEmma

I still have all the screenies I took of my carb setup before I removed the addon so I could use my setup with a new installation, but there's 61 pictures which is a lot to upload here... So instead I'm creating an imgur album which'll hopefully be public to you guys... in the hope that you might know or can pinpoint what it is that does that it's not working as it should.

**Comment by Swirrel** [comment]
You're a darling. you moved it :) the Show Instance Map. Sweet!

**Comment by IrcDirk** [comment]
So is this solved? If yes, then please close.

**Comment by Swirrel** [comment]
No it's not solved. I'm still missing them. even with a fresh installation of Carbonite.

**Comment by IrcDirk** [comment]
Fresh u mean reseted to defaults?

**Comment by Swirrel** [comment]
I completely removed carbonite from my computer (not just from the addon folder). including ALL settings. Got a fresh Carbonite installation and still have the issue. And yes turning off everything except for carbonite and I still have the problem. I can't tell you why.

**Comment by IrcDirk** [comment]
U know that setting are in WTF folder? I need to be sure u know how to find them.

**Comment by IrcDirk** [comment]
Ok, i know what your problem u need to enable **Show Guide POIs**, without this setting u will not see Flight Masters. This is screen u posted in gallery:

![guide pois](https://i.imgur.com/b53Ey3y.png)

BTW. if u want to reset whole Carbonite settings u need to delete Carbonite*.lua in WTF\Account\ACCOUNT#NUMBER\SavedVariables folder.

**Comment by Swirrel** [comment]
> BTW. if u want to reset whole Carbonite settings u need to delete Carbonite*.lua in WTF\Account\ACCOUNT#NUMBER\SavedVariables folder. 
I removed that too as it's included in everything. When I was done, I had nothing left on my entire computer that so much as mentioned the name as we know it aka Carbonite. Got it?

I have tried it. There it is: I - Have - Tried - it & it - does - not - work.

And to mention, I don't want a gazillion stuff on my map, neither if it's small or big. I don't want to know about Bonus locations, profession trainers, Drink/food vendors, reagent vendors ect.
I just want the vanished-in-to-thin-air flightpoints back from the living dead.

![wowscrnshot_092617_221706](https://user-images.githubusercontent.com/31900265/30882334-e26a3f34-a308-11e7-9ecc-2a0d33f2bfcc.jpg)
![wowscrnshot_092617_221717](https://user-images.githubusercontent.com/31900265/30882332-e264cd24-a308-11e7-96e7-c38fb25d2318.jpg)
![wowscrnshot_092617_221731](https://user-images.githubusercontent.com/31900265/30882331-e2637866-a308-11e7-8a0c-569ee207bdb8.jpg)
![wowscrnshot_092617_221745](https://user-images.githubusercontent.com/31900265/30882333-e2690c5e-a308-11e7-96bd-a3522f2f27d3.jpg)

An FYI... the screenies you're referring to was taken by me for my sake so I could set up Carbonite in the exact same manner AFTER I'd deleted the entire thing. I then there after decided to post them here, so you guys could help me figure out what I was missing.

Here's what I want back: mousing on Felblaze Ingress, Azsuna: 
![wowscrnshot_092617_223314](https://user-images.githubusercontent.com/31900265/30882924-dc1d02c2-a30a-11e7-9fb6-bec26f1e6816.jpg)
Yes that's the Blizzard map which thank god I have on speed-dial. I'm missing the teeny tiny lightning shaped yellow'ish faded icons indicating that "here's a flight master"

**Comment by Swirrel** [comment]
I got teamviewer and a link available to my discord server, I got skype too if that's better. You're more than welcome to have a voice-com chat with me while poking through my addons to try and find what's wrong.

**Comment by Palonblade** [comment]
Wow! These fellows work on this addon in their spare time and for nothing in return and are trying to help. Your problem appears to be insidious and there are a lot of changes going on so criticizing them is not terribly helpful. If you could, please post a screenshot of your current scale settings.

**Comment by mikepauer** [comment]
Erm, well I found one problem with what your saying... Carbonite has never had teeny tiny lightning shaped icons for flightmasters.

Carbonite draws it's flightmasters as a wyvern head icon, and what IrcDirk said earlier is exactly how to get Carbonite to draw it's flightmasters. 

The option "Show Guide POI's" causes the map to display banks, mailboxes, flightmasters, teleport hubs (Argus), Auctioneers and Innkeepers. Nothing else.

**Comment by IrcDirk** [comment]
@Swirrel give me your discord, i will connect to your PC through TeamVierwer and i will see what i can do.

And how @mikepauer writes filghtmasters are wyvern head icons.

**Comment by IrcDirk** [comment]
Ok, when u wrote about other Flight Master icons, something flashed in my mind... and yes there were other icons for Flight masters some time ago... So i got in the code and found fix for this. 

Pushed. Try now. It should be fine now.

**Comment by Swirrel** [comment]
**Palonblade:** I do appreciate their hard work. I know you can't tell. At least you don't know how the post looked like before I removed half of it. It's frustration at it's worst. None of what I've written is critique. I rarely ever have Carbonite issue (this might be my fourth or fifth since the early days of TBC), so when I do and it starts bugging me to a point where I my self, can't fix it (which btw, doesn't happen often), I feel compelled to turn to the best ppl on the planet that might be able to help. And these guys are it. The best people on the planet to help with a Carbonite issue - which is why I'm here.
I can't imagine that it isn't also as frustrating to them as it is to me however perhaps on a whole different level. 
_So next time, before you verbally bitch slap me, make sure you know me._ 
Other than that, you're right. I haven't said a lot of "Thank you's" but if you look closer, they are there.

**mikepauer:** Strange. makes no sense to me, I'm positive there once was a different FP icon.. However neither do I want or need clutter (imo it's clutter) on my map. I'll take the flightmasters, but not the others: auctioneers, banks or mailboxes. I got minimap for that and that's a completely different addon. 

**IrcDirk:** discord: https://discord.gg/jMGZ6b - Thank you

**Comment by Swirrel** [comment]
IrcDirk: Does that mean I should get Carbonite from here? Cus my twitch click can't find any new updates for carb though all of carb is set to alpha.

**Comment by IrcDirk** [comment]
Curse updates are sometimes delayed in time because moderators have to accept them. Just wait a bit, new Alpha should be there in some time.

**Comment by xSimone** [comment]
Curse is botched I find. I installed Carbonite from there and things weren't working like the map wasn't opening, etc.. 

I deleted it, downloaded the Master from here and it works 100%. 

Did this around a couple days back. I suggest always downloading from the GitHub ;x

**Comment by IrcDirk** [comment]
@xSimone U need to use Alpha builds to have 100% the same as in GitHub, normally it downloads Releases only.

**Comment by xSimone** [comment]
I did that but it seems to just play out weirdly. I don't know. :f I just download from here as my experiences don't bode well with Curse Client...

**Comment by Swirrel** [comment]
I think the Twitch ppl are still in bed. hehe

**Comment by Swirrel** [comment]
Wauw! They're slow at Twitch.. 7hrs slow.

**Comment by Palonblade** [comment]
If you could, please post a screenshot of your current scale settings.

**Comment by Swirrel** [comment]
Twitch had updates.

And they're back! YEAH!
Now I can also see those new transportation hubs that came with Argus, on my map. And I have no bank, auctioneer, mailboxes on my map. YEAH!

IrcDirk: You're a god. Thank you doesn't even begin to cover my gratitude, but at this day of the month it's the best I have. Hitch me a link to a donation button so I know where to put it when it's the last day of the month. The least I can do is donate some money. That may not be why you did it, but all the same. Thank you.

Thank you!

See, flightmaster icons are back: https://i.imgur.com/5dmRks3.jpg

**Comment by Swirrel** [comment]
Totally hyped. yeah.. and on raid day none the less... YEAH!

**Comment by IrcDirk** [comment]
Donations goes to Rythal but for all work he did in past years alone he deserves it.

Good to know that all works fine know :) Curse/Twitch workes work from 9 till 15 CST so sometimes updates are delayed for a long time.

**Comment by Swirrel** [comment]
To Rythal then. I need a link to a donations button to him then...

Denmark, where I'm from, runs on GMT+1 atm when it's winter and +2 when it's summer and time zones wasn't a lot if any at all, that we had in school so I've never really learned it. I'm guessing though that CST is Central Standard Time and I've no idea what that is in comparison to GMT

**Comment by IrcDirk** [comment]
![donate](https://i.imgur.com/QPmnxE3.png)

As to time its like -6 hours i think.

**Comment by fdellwing** [comment]
https://www.timeanddate.com/worldclock/converter.html?iso=20170928T090000&p1=tz_gmt&p2=tz_ct&p3=136&p4=tz_cest Have fun ;)

**Comment by Swirrel** [comment]
Thanks guys :)

**Comment by Swirrel** [comment]
Donation done.
